spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:inspur
    username: scott
    password: tiger
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


