spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
      username: scott
      password: tiger
      url: jdbc:oracle:thin:@localhost:1521:inspur
      driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: aop-demo
      repositories:
        enabled: true